# Generated by Django 5.1.3 on 2024-12-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('probeg', models.IntegerField(default=0)),
                ('max_speed', models.IntegerField(default=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.brend')),
            ],
        ),
    ]
