# Generated by Django 5.1.3 on 2024-12-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='sotuvda_bormi',
            field=models.BooleanField(default=True),
        ),
    ]
